language: node_js
node_js:
  - "6.7"
services:
  - -mongodb
before_script:
  - cd node
  - npm install -g mocha
  - npm install
script: 
  - npm test
  - cd ..
  - zip -r ASE *
  - travis setup releases
deploy:
  provider: releases
  file: ASE.zip
  skip_cleanup: true
  on:
    tags: true