language: node_js
node_js:
  - "6.7"
services:
  - -mongodb
before_script:
  - cd node
  - npm install -g mocha
  - npm install
script: 
  - npm test
  - cd ..
  - zip -r ASE *
deploy:
  provider: releases
  api_key: "VWeV29hWJtjLssL9s8gy"
  file: ASE.zip
  skip_cleanup: true
  on:
    tags: true
  all_branches: true
