language: node_js
node_js:
- '6.7'
services:
- "-mongodb"
before_script:
- cd node
- npm install -g mocha
- npm install
script:
- npm test
- cd ..
- zip -r ASE *
deploy:
  provider: releases
  file: ASE.zip
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: 4KVQPfojXEecYRlJga/pOA1xOc2gqgT0D4bfT1UpHJMcw32YU12FtyWk+AWIkWGhN2mgh13plIyu+6hEKF0kSHk9V6ILikWD10zRfzk3C6YYgphHfJtQZZvQKMX1WnA1rn8j5E1B8shS92Ozt45CzVfNfg/8i4cDmSkKvNWUtDQAPr797oP7efFSFpTDFWNARuKGlJh4M/Txv4ZcGO2+gYb+//VKgREfaliuilMYSgM3v+VM82i17eH4ofdK7dDGQFe1E58jABYEdaeb3TBY6s/9CwwkL2zLSGr9qPHNOa2YqQEdAglVM9tkqB8N2p1wj0NjrqTlXhDwAAL06q3oNaKm+8Txl4i9zxSZIOF9dH93yGFKDqgZTLGhJJHwV8sLXFnjo8PGo1ZpRDcntoY/lFRzBUN39ZgTIBtLYEM+Y+Q1FX5qV6tGjHa+OqYg8r+zdgxc5XhnzoMn8Od0u1mUaQT+trAJEZyCI7/wcnuCOiJtBaF5QmyTahskrkgpJQKL0GtFDbkvomM0Jhj3KyDAbGSO2bLzgEGROBOhmzUshFKm3+HBqTN2S9hGYo0vcNAHr/pmWOdf/iWxdFww+mNvN2Cjfyj/MmV+sSD6ITLh4QXvynmlBOzj4n7x49UKZUaDnAKP0tpg4kQ6vgqphVByn7tHlCMf5WWX1ujMhLd4pm4=
