language: node_js
node_js:
  - "6.7"
services:
  - -mongodb
before_script:
  - cd node
  - npm install -g mocha
  - npm install
  - npm install travis-encrypt -g
  - travis-encrypt -r kai-oswald/ASE -k GH_TOKEN -v
script: 
  - npm test
  - cd ..
  - zip -r ASE *
deploy:
  provider: releases
  file: ASE.zip
  skip_cleanup: true
  on:
    tags: true